simple test and package

diff --git a/.github/workflows/pr-verify.yml b/.github/workflows/pr-verify.yml
--- a/.github/workflows/pr-verify.yml
+++ b/.github/workflows/pr-verify.yml
@@ -112,11 +112,55 @@ jobs:
 
       - name: Cargo build
         run: make build
+  test_binary:
+    name: Run tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Install Rust Toolchain
+        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
+        with:
+          toolchain: stable
+          default: true
+          profile: minimal
+          target: wasm32-unknown-unknown
+      - name: Copy library to c_example
+        run: cp target/debug/libgraph_sdk_ffi.so bridge/ffi/src/c_example/
+      - name: Generate bindgen
+        run: make bindgen
+      - name: Build main binary
+        run: cd bridge/ffi/src/c_example/ && gcc main.c -L. -lgraph_sdk_ffi -o main
+      - name: Run main binary
+        id: run-main
+        run: |
+          export LD_LIBRARY_PATH=bridge/ffi/src/c_example/
+          output=$(./main)
+          echo "$output"
+          echo "::set-output name=output::$output"
+      - name: Check test result
+        run: |
+          if [[ "${{ steps.run-main.outputs.output }}" == *"passed"* ]]; then
+            echo "All tests passed!"
+          else
+            echo "Some tests failed!"
+            exit 1
+          fi
+      - name: Upload artifacts graph_sdk_ffi.h and libgraph_sdk_ffi.so
+        uses: actions/upload-artifact@v2
+        with:
+          name: graph_sdk_ffi
+          path: |
+            bridge/ffi/src/c_example/graph_sdk_ffi.h
+            bridge/ffi/src/c_example/libgraph_sdk_ffi.so
+            bridge/ffi/src/c_example/main.c
 
   generate-docs:
     name: Generate graph sdk rust docs
     runs-on: ubuntu-latest
-    needs: [verify, test, lint, build]
+    needs: [verify, test, lint, build, test_binary]
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
